# -*- coding: utf-8 -*-
"""data analisis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqMY26KkddEBBMPvkpILpB2XQg9iNNQn
"""

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'Archivo subido: {filename}')

eventos_df = pd.read_csv(filename)

print(eventos_df.head())

print(eventos_df.columns)

if 'idioma' in eventos_df.columns:
    idioma_counts = eventos_df['idioma'].value_counts()

    idioma_counts.plot(kind='bar', figsize=(10, 6))

    plt.title('Cantidad de eventos por idioma')
    plt.xlabel('Idioma')
    plt.ylabel('Cantidad de Eventos')
    plt.xticks(rotation=45)
    plt.grid(True)
    plt.show()
else:
    print("La columna no existe en el DataFrame.")

import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'Archivo subido: {filename}')

eventos_df = pd.read_csv(filename)

print(eventos_df.head())

print(eventos_df.columns)

if 'tipo_evento' in eventos_df.columns:
    Tipo_evento_counts = eventos_df['tipo_evento'].value_counts()
    Tipo_evento_counts.plot(kind='pie', figsize=(8, 8), autopct='%1.1f%%', startangle=90)
    plt.title('Distribución de Modalidades de Eventos')
    plt.ylabel('')
    plt.legend(Tipo_evento_counts.index, loc='best')
    plt.show()
else:
    print("La columna no existe en el DataFrame.")